# Generated by Django 3.0.1 on 2020-01-01 14:38

from django.db import migrations, models
import django.db.models.deletion
import file_uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('regnskab', 'Regnskab'), ('referat', 'Referat'), ('andet', 'Andet')], max_length=200)),
                ('date', models.DateField()),
                ('doc', models.FileField(upload_to=file_uploader.models.get_upload_path)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
